import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from 'react'
import { supabase } from './supabase'

export type User={id:string;name:string;email:string;role:'Member'|'Admin';joinedAt:string}
type AuthContextValue={user:User|null;loading:boolean;signIn:(email:string,password:string)=>Promise<void>;signUp:(name:string,email:string,password:string)=>Promise<void>;signOut:()=>void;updateProfile:(name:string)=>void}
const STORAGE_KEY='haven-auth-user';const AuthContext=createContext<AuthContextValue|null>(null)
function mapUser(value:{id:string;email?:string|null;created_at:string;user_metadata?:Record<string,unknown>;app_metadata?:Record<string,unknown>}):User{return{id:value.id,name:String(value.user_metadata?.full_name??value.email?.split('@')[0]??'Member'),email:value.email??'',role:value.app_metadata?.role==='admin'?'Admin':'Member',joinedAt:value.created_at}}
export function AuthProvider({children}:{children:ReactNode}){const [user,setUser]=useState<User|null>(null);const [loading,setLoading]=useState(true)
 useEffect(()=>{if(supabase){void supabase.auth.getSession().then(({data})=>{setUser(data.session?.user?mapUser(data.session.user):null);setLoading(false)});const {data}=supabase.auth.onAuthStateChange((_event,session)=>{setUser(session?.user?mapUser(session.user):null);setLoading(false)});return()=>data.subscription.unsubscribe()}const saved=localStorage.getItem(STORAGE_KEY);if(saved){try{setUser(JSON.parse(saved) as User)}catch{localStorage.removeItem(STORAGE_KEY)}}setLoading(false)},[])
 const persist=(next:User|null)=>{setUser(next);if(next)localStorage.setItem(STORAGE_KEY,JSON.stringify(next));else localStorage.removeItem(STORAGE_KEY)}
 const value=useMemo<AuthContextValue>(()=>({user,loading,signIn:async(email,password)=>{if(supabase){const {data,error}=await supabase.auth.signInWithPassword({email,password});if(error)throw new Error(error.message);if(!data.user)throw new Error('Sign in could not be completed.');setUser(mapUser(data.user));return}if(password.length<8)throw new Error('Password must be at least 8 characters.');const name=email.split('@')[0].split(/[._-]/).map(part=>part.charAt(0).toUpperCase()+part.slice(1)).join(' ');persist({id:crypto.randomUUID(),name,email,role:email.toLowerCase().endsWith('@havenly.com')?'Admin':'Member',joinedAt:new Date().toISOString()})},signUp:async(name,email,password)=>{if(supabase){const {data,error}=await supabase.auth.signUp({email,password,options:{data:{full_name:name}}});if(error)throw new Error(error.message);if(!data.user)throw new Error('Account could not be created.');setUser(mapUser(data.user));return}if(password.length<8)throw new Error('Password must be at least 8 characters.');persist({id:crypto.randomUUID(),name,email,role:'Member',joinedAt:new Date().toISOString()})},signOut:()=>{if(supabase)void supabase.auth.signOut();persist(null)},updateProfile:name=>{if(user)persist({...user,name});if(supabase)void supabase.auth.updateUser({data:{full_name:name}})}}),[user,loading]);return <AuthContext.Provider value={value}>{children}</AuthContext.Provider>}
export function useAuth(){const context=useContext(AuthContext);if(!context)throw new Error('useAuth must be used inside AuthProvider');return context}
