import { Agent, run } from 'npm:@openai/agents'
import { z } from 'npm:zod'
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2'
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type'}
const searchSchema=z.object({filters:z.object({query:z.string(),city:z.string(),area:z.string(),minPrice:z.string(),maxPrice:z.string(),minSquareFeet:z.string(),maxSquareFeet:z.string(),bedrooms:z.string(),bathrooms:z.string(),purpose:z.enum(['','sale','rent']),propertyType:z.enum(['','house','apartment','villa','townhouse','land','commercial']),sort:z.enum(['newest','oldest','price-low','price-high'])}),summary:z.string(),assumptions:z.array(z.string())})
const schemas={title:z.object({title:z.string().min(5).max(100)}),description:z.object({description:z.string().min(30).max(3000)}),price:z.object({suggestedPrice:z.number().positive(),low:z.number().positive(),high:z.number().positive(),confidence:z.number().min(0).max(100),rationale:z.string(),currency:z.string()}),search:searchSchema,recommend:z.object({propertyIds:z.array(z.string()).max(6),reason:z.string()}),chat:z.object({answer:z.string().max(1500),suggestedPrompts:z.array(z.string()).max(4),propertyIds:z.array(z.string()).max(5)})} as const
const instructions={title:'Create one specific, truthful, premium property listing title. Never invent features. Return structured output.',description:'Write a polished, fair-housing-compliant property description from only supplied facts. Do not invent amenities, views, schools, distances, or guarantees. Avoid discriminatory language. Return structured output.',price:'Act as a conservative property valuation assistant. Analyze supplied listing facts and comparables. Give a range, confidence, and concise rationale. Never present as an appraisal. Return structured output.',search:'Convert multilingual property intent into structured search filters. Understand Pakistani units: 1 crore PKR=10,000,000 and 1 lakh=100,000. DHA is an area. Preserve unknown concepts in query or assumptions. Use empty strings when unspecified. Return structured output.',recommend:'Rank only IDs from the supplied catalog by location, type, budget proximity, bedrooms, and purpose. Never output an unknown ID. Explain the match briefly. Return structured output.',chat:'You are Haven AI, a concise property marketplace assistant. Answer from supplied catalog and app context. Never provide legal, financial, or appraisal certainty. Recommend only supplied property IDs. For a property search, mention useful constraints and provide matching IDs. Return structured output.'} as const
Deno.serve(async(req)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});try{const auth=req.headers.get('Authorization');if(!auth)return response({error:'Authentication required'},401);const supabase=createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_ANON_KEY')!,{global:{headers:{Authorization:auth}}});const {data:{user}}=await supabase.auth.getUser();if(!user)return response({error:'Authentication required'},401);const {task,payload}=await req.json();if(!(task in schemas))return response({error:'Unsupported AI task'},400);const input=JSON.stringify(payload);if(input.length>30000)return response({error:'Request is too large'},413);const {data:allowed,error:rateError}=await supabase.rpc('consume_ai_quota',{operation:task});if(rateError||!allowed)return response({error:'AI usage limit reached. Try again shortly.'},429);const agent=new Agent({name:`Haven ${task} agent`,instructions:instructions[task as keyof typeof instructions],model:Deno.env.get('OPENAI_MODEL')??'gpt-4.1-mini',outputType:schemas[task as keyof typeof schemas]});const result=await run(agent,input,{maxTurns:4});if(!result.finalOutput)throw new Error('Agent returned no result');return response({result:result.finalOutput},200)}catch(error){console.error('AI function error',error);return response({error:'AI request could not be completed'},500)}})
function response(body:unknown,status:number){return new Response(JSON.stringify(body),{status,headers:{...cors,'Content-Type':'application/json','Cache-Control':'no-store'}})}
