import { useEffect, useMemo, useRef, useState } from 'react'
import { Link } from 'react-router-dom'
import { Bath, BedDouble, Building2, ChevronLeft, ChevronRight, Filter, Heart, ListFilter, LoaderCircle, MapPin, Search, SlidersHorizontal, Sparkles, Square, X } from 'lucide-react'
import { Button, EmptyState, Input } from '../../components/ui'
import { useProperties } from '../properties/property-store'
import type { Property } from '../properties/types'
import { defaultFilters, marketplaceFixtures, searchProperties, suggestions, type SearchFilters, type SortOption } from './search-service'
import { aiService } from '../ai/ai-service'
import { useToast } from '../../components/ui'
import { KARACHI_AREAS, KARACHI_CITY } from '../../lib/karachi'

const PAGE_SIZE=6
const field='h-10 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm outline-none focus:border-teal-500 dark:border-slate-700 dark:bg-slate-900'
export function PropertySearchPage(){
 const {properties,loading,error,refresh}=useProperties(); const all=useMemo(()=>[...properties,...marketplaceFixtures],[properties]); const [filters,setFilters]=useState<SearchFilters>(defaultFilters); const [applied,setApplied]=useState<SearchFilters>(defaultFilters); const [page,setPage]=useState(1); const [visible,setVisible]=useState(PAGE_SIZE); const [infinite,setInfinite]=useState(false); const [mobile,setMobile]=useState(false); const [suggestOpen,setSuggestOpen]=useState(false); const sentinel=useRef<HTMLDivElement>(null)
 const [aiLoading,setAiLoading]=useState(false);const [aiSummary,setAiSummary]=useState('');const {toast}=useToast()
 const results=useMemo(()=>searchProperties(all,applied),[all,applied]); const pageCount=Math.max(1,Math.ceil(results.length/PAGE_SIZE)); const displayed=infinite?results.slice(0,visible):results.slice((page-1)*PAGE_SIZE,page*PAGE_SIZE); const options=suggestions(all,filters.query); const cities=[KARACHI_CITY]; const areas=KARACHI_AREAS; const active=Object.entries(applied).filter(([k,v])=>k!=='sort'&&v).length
 useEffect(()=>{if(!infinite||!sentinel.current)return;const observer=new IntersectionObserver(([entry])=>{if(entry.isIntersecting)setVisible(n=>Math.min(n+PAGE_SIZE,results.length))},{rootMargin:'300px'});observer.observe(sentinel.current);return()=>observer.disconnect()},[infinite,results.length])
 const set=<K extends keyof SearchFilters>(key:K,value:SearchFilters[K])=>setFilters(f=>({...f,[key]:value})); const apply=()=>{setApplied(filters);setPage(1);setVisible(PAGE_SIZE);setMobile(false)}; const clear=()=>{setFilters(defaultFilters);setApplied(defaultFilters);setPage(1)}
 const aiSearch=async()=>{if(!filters.query.trim()){apply();return}setAiLoading(true);try{const result=await aiService.search(filters.query);const next={...result.filters,query:''};setFilters(next);setApplied(next);setAiSummary(result.summary);setSuggestOpen(false);setPage(1);setVisible(PAGE_SIZE);if(result.assumptions.length)toast(result.assumptions.join(' '))}catch(e){toast(e instanceof Error?e.message:'AI search failed.','error')}finally{setAiLoading(false)}}
 return <div className="mx-auto max-w-7xl">
  <div className="rounded-3xl bg-[#073b3a] px-5 py-8 text-white sm:px-9"><p className="flex items-center gap-2 text-xs font-bold uppercase tracking-[.2em] text-teal-300"><Sparkles className="size-4"/>AI property discovery</p><h1 className="mt-3 font-display text-3xl font-semibold sm:text-4xl">Find a place that fits your life.</h1><p className="mt-2 text-sm text-teal-50/65">Describe your ideal property naturally. Haven AI turns intent into precise filters.</p><div className="relative mt-7 max-w-3xl"><Sparkles className="absolute left-4 top-4 size-5 text-teal-600"/><input value={filters.query} onChange={e=>{set('query',e.target.value);setSuggestOpen(true)}} onFocus={()=>setSuggestOpen(true)} onKeyDown={e=>{if(e.key==='Enter')void aiSearch()}} className="h-13 w-full rounded-2xl bg-white pl-12 pr-32 text-sm text-slate-900 outline-none" placeholder="e.g. I need a 5 Marla house in DHA under 2 Crore"/><button onClick={()=>void aiSearch()} disabled={aiLoading} className="absolute right-1.5 top-1.5 flex h-10 items-center gap-2 rounded-xl bg-teal-600 px-5 text-sm font-bold disabled:opacity-60">{aiLoading?<LoaderCircle className="size-4 animate-spin"/>:<Sparkles className="size-4"/>}AI Search</button>{suggestOpen&&options.length>0&&<div className="absolute inset-x-0 top-15 z-30 rounded-2xl bg-white p-2 text-slate-800 shadow-2xl">{options.map(o=><button key={o} onClick={()=>{set('query',o);setSuggestOpen(false);setApplied({...filters,query:o})}} className="flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-sm hover:bg-slate-50"><MapPin className="size-4 text-teal-600"/>{o}</button>)}</div>}</div>{aiSummary&&<p className="mt-4 flex items-center gap-2 text-xs text-teal-100"><Sparkles className="size-3"/>{aiSummary}</p>}</div>
  <div className="mt-4 flex flex-wrap items-center gap-3 rounded-2xl border border-teal-200 bg-teal-50 p-3 dark:border-teal-900 dark:bg-teal-950/40"><span className="flex items-center gap-2 text-xs font-bold text-teal-800 dark:text-teal-200"><Sparkles className="size-4"/>Natural language search</span><button onClick={()=>void aiSearch()} disabled={aiLoading||!filters.query.trim()} className="flex items-center gap-2 rounded-xl bg-teal-600 px-4 py-2 text-xs font-bold text-white disabled:opacity-50">{aiLoading?<LoaderCircle className="size-4 animate-spin"/>:<Sparkles className="size-4"/>}Interpret with AI</button><span className="text-xs text-slate-500">Try: “I need a 5 Marla house in DHA under 2 Crore.”</span></div>{aiSummary&&<p className="mt-3 rounded-xl bg-white px-4 py-3 text-sm text-slate-600 shadow-sm dark:bg-slate-900 dark:text-slate-300"><strong className="text-teal-700">Haven AI:</strong> {aiSummary}</p>}
  <div className="mt-6 grid items-start gap-6 lg:grid-cols-[270px_1fr]">
   <aside className={`${mobile?'fixed inset-0 z-50 overflow-y-auto bg-white p-5 dark:bg-slate-950':'hidden'} lg:sticky lg:top-24 lg:block`}><div className="flex items-center justify-between"><h2 className="flex items-center gap-2 font-semibold"><SlidersHorizontal className="size-4"/>Filters {active>0&&<span className="rounded-full bg-teal-600 px-2 text-xs text-white">{active}</span>}</h2><button onClick={()=>setMobile(false)} className="lg:hidden"><X/></button></div><div className="mt-5 space-y-5 rounded-2xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><Select label="City" value={filters.city} onChange={v=>{set('city',v);set('area','')}} options={cities}/><Select label="Area" value={filters.area} onChange={v=>set('area',v)} options={areas}/><div><Label>Price range</Label><div className="grid grid-cols-2 gap-2"><Input type="number" value={filters.minPrice} onChange={e=>set('minPrice',e.target.value)} placeholder="Min"/><Input type="number" value={filters.maxPrice} onChange={e=>set('maxPrice',e.target.value)} placeholder="Max"/></div></div><Select label="Bedrooms" value={filters.bedrooms} onChange={v=>set('bedrooms',v)} options={['1','2','3','4','5']} suffix="+ beds"/><Select label="Bathrooms" value={filters.bathrooms} onChange={v=>set('bathrooms',v)} options={['1','2','3','4']} suffix="+ baths"/><Select label="Purpose" value={filters.purpose} onChange={v=>set('purpose',v as SearchFilters['purpose'])} options={['sale','rent']}/><Select label="Property type" value={filters.propertyType} onChange={v=>set('propertyType',v as SearchFilters['propertyType'])} options={['house','apartment','villa','townhouse','land','commercial']}/><Button className="w-full" onClick={apply}>Show properties</Button><button onClick={clear} className="w-full text-xs font-bold text-slate-500">Reset filters</button></div></aside>
   <main><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="font-display text-xl font-semibold">{results.length} properties found</p><p className="text-xs text-slate-500">Instant results from indexed listings</p></div><div className="flex gap-2"><Button variant="secondary" className="lg:hidden" onClick={()=>setMobile(true)}><Filter className="size-4"/>Filters</Button><select aria-label="Sort results" className={`${field} w-40`} value={applied.sort} onChange={e=>{const sort=e.target.value as SortOption;set('sort',sort);setApplied(f=>({...f,sort}));setPage(1)}}><option value="newest">Newest</option><option value="oldest">Oldest</option><option value="price-low">Price: low</option><option value="price-high">Price: high</option></select></div></div>
   {active>0&&<div className="mt-4 flex flex-wrap gap-2">{Object.entries(applied).filter(([k,v])=>k!=='sort'&&v).map(([key,value])=><button key={key} onClick={()=>{const next={...applied,[key]:''};setApplied(next);setFilters(next)}} className="flex items-center gap-1 rounded-full bg-teal-50 px-3 py-1.5 text-xs font-semibold text-teal-800 dark:bg-teal-950 dark:text-teal-300">{String(value)}<X className="size-3"/></button>)}</div>}
   {loading?<div className="mt-6 grid gap-5 sm:grid-cols-2 xl:grid-cols-3">{[1,2,3].map(item=><div key={item} className="h-80 animate-pulse rounded-2xl bg-slate-200 dark:bg-slate-800"/>)}</div>:error?<div className="mt-6 rounded-2xl border border-rose-200 bg-rose-50 p-6 text-center dark:border-rose-900 dark:bg-rose-950/30"><p className="font-semibold text-rose-700 dark:text-rose-300">Marketplace listings could not be loaded</p><p className="mt-1 text-sm text-rose-600/70">This is a connection or database policy issue, not an empty search result.</p><Button className="mt-4" variant="secondary" onClick={()=>void refresh()}>Try again</Button></div>:displayed.length===0?<div className="mt-6"><EmptyState icon={<Building2/>} title="No published properties match" description="Discover only shows Published listings. Draft, archived, sold, and rejected properties remain private and cannot be found from another account or by Haven AI."/></div>:<div className="mt-5 grid gap-5 sm:grid-cols-2 xl:grid-cols-3">{displayed.map(p=><SearchCard key={p.id} property={p}/>)}</div>}
   {infinite?<><div ref={sentinel} className="h-8"/>{visible<results.length&&<p className="text-center text-xs text-slate-400">Loading more…</p>}</>:results.length>PAGE_SIZE&&<Pagination page={page} count={pageCount} setPage={setPage}/>}<div className="mt-6 flex justify-center gap-2 text-xs text-slate-500"><ListFilter className="size-4"/>Mode:<button onClick={()=>{setInfinite(!infinite);setVisible(PAGE_SIZE);setPage(1)}} className="font-bold text-teal-700">Switch to {infinite?'pagination':'infinite scroll'}</button></div></main>
  </div>
 </div>
}
function SearchCard({property:p}:{property:Property}){const [liked,setLiked]=useState(false);return <article className="overflow-hidden rounded-2xl border border-slate-200 bg-white transition hover:-translate-y-1 hover:shadow-xl dark:border-slate-800 dark:bg-slate-900"><div className="relative aspect-[4/3] overflow-hidden"><Link to={`/dashboard/property/${p.id}`}><img src={p.images[0]} alt={p.title} loading="lazy" className="h-full w-full object-cover"/></Link><span className="absolute left-3 top-3 rounded-lg bg-white/90 px-2 py-1 text-[10px] font-bold uppercase text-slate-700">For {p.purpose}</span><button onClick={()=>setLiked(!liked)} className="absolute right-3 top-3 grid size-9 place-items-center rounded-full bg-white/90"><Heart className={`size-4 ${liked?'fill-rose-500 text-rose-500':'text-slate-700'}`}/></button></div><div className="p-4"><p className="text-xs text-slate-500">{p.propertyType} · {p.area}</p><Link to={`/dashboard/property/${p.id}`}><h3 className="mt-1 truncate font-display text-lg font-semibold hover:text-teal-700">{p.title}</h3></Link><p className="mt-1 flex gap-1 text-xs text-slate-500"><MapPin className="size-3"/>{p.city}</p><p className="mt-4 font-display text-xl font-bold text-teal-700">${p.price.toLocaleString()}<span className="text-xs text-slate-400">{p.purpose==='rent'?' / mo':''}</span></p><div className="mt-4 flex gap-4 border-t border-slate-100 pt-3 text-xs text-slate-500 dark:border-slate-800"><span className="flex gap-1"><BedDouble className="size-4"/>{p.bedrooms}</span><span className="flex gap-1"><Bath className="size-4"/>{p.bathrooms}</span><span className="flex gap-1"><Square className="size-4"/>{p.squareFeet.toLocaleString()} ft²</span></div></div></article>}
function Label({children}:{children:React.ReactNode}){return <label className="mb-2 block text-xs font-bold uppercase text-slate-500">{children}</label>}
function Select({label,value,onChange,options,suffix=''}:{label:string;value:string;onChange:(v:string)=>void;options:readonly string[];suffix?:string}){return <div><Label>{label}</Label><select className={field} value={value} onChange={e=>onChange(e.target.value)}><option value="">Any {label.toLowerCase()}</option>{options.map(o=><option key={o} value={o}>{o.charAt(0).toUpperCase()+o.slice(1)}{suffix}</option>)}</select></div>}
function Pagination({page,count,setPage}:{page:number;count:number;setPage:(n:number)=>void}){return <nav className="mt-8 flex justify-center gap-1"><button disabled={page===1} onClick={()=>setPage(page-1)} className="grid size-9 place-items-center disabled:opacity-30"><ChevronLeft className="size-4"/></button>{Array.from({length:count},(_,i)=>i+1).map(n=><button key={n} onClick={()=>setPage(n)} className={`size-9 rounded-lg text-sm font-semibold ${page===n?'bg-teal-600 text-white':'hover:bg-slate-100'}`}>{n}</button>)}<button disabled={page===count} onClick={()=>setPage(page+1)} className="grid size-9 place-items-center disabled:opacity-30"><ChevronRight className="size-4"/></button></nav>}
