import { useState } from 'react'
import { DollarSign, FileText, LoaderCircle, Sparkles, Type } from 'lucide-react'
import { Button, useToast } from '../../components/ui'
import { aiService } from './ai-service'
import { marketplaceFixtures } from '../search/search-service'
import type { PropertyFormValues } from '../properties/schema'

type Field='title'|'description'|'price'
export function AIListingTools({values,apply}:{values:PropertyFormValues;apply:(field:Field,value:string|number)=>void}){const [busy,setBusy]=useState<Field|null>(null);const {toast}=useToast();const generate=async(field:Field)=>{setBusy(field);try{if(field==='title'){const result=await aiService.title(values);apply(field,result.title)}else if(field==='description'){const result=await aiService.description(values);apply(field,result.description)}else{const result=await aiService.price(values,marketplaceFixtures);apply(field,result.suggestedPrice);toast(`AI range: PKR ${result.low.toLocaleString()}–${result.high.toLocaleString()} · ${result.confidence}% confidence. ${result.rationale}`)}if(field!=='price')toast(`AI ${field} suggestion applied. Review it before publishing.`)}catch(error){toast(error instanceof Error?error.message:'AI generation could not be completed.','error')}finally{setBusy(null)}};return <section className="mb-6 rounded-2xl border border-teal-200 bg-gradient-to-r from-teal-50 via-white to-white p-4 dark:border-teal-900 dark:from-teal-950/50 dark:via-slate-900 dark:to-slate-900"><div className="flex flex-wrap items-center gap-2"><span className="mr-2 flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-teal-700 dark:text-teal-300"><Sparkles className="size-4"/>AI listing studio</span><ToolButton label="Generate title" icon={<Type className="size-4"/>} loading={busy==='title'} disabled={busy!==null} click={()=>void generate('title')}/><ToolButton label="Write description" icon={<FileText className="size-4"/>} loading={busy==='description'} disabled={busy!==null} click={()=>void generate('description')}/><ToolButton label="Suggest price" icon={<DollarSign className="size-4"/>} loading={busy==='price'} disabled={busy!==null} click={()=>void generate('price')}/></div><p className="mt-3 text-[11px] text-slate-500">Haven AI uses only entered property facts and comparable listings. Suggestions are not appraisals; verify all content before publishing.</p></section>}
function ToolButton({label,icon,loading,disabled,click}:{label:string;icon:React.ReactNode;loading:boolean;disabled:boolean;click:()=>void}){return <Button type="button" variant="secondary" disabled={disabled} onClick={click}>{loading?<LoaderCircle className="size-4 animate-spin"/>:icon}{label}</Button>}
