import { useEffect, useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { ArrowRight, Building2, LoaderCircle, Sparkles } from 'lucide-react'
import { Button, EmptyState, useToast } from '../../components/ui'
import { useProperties } from '../properties/property-store'
import { marketplaceFixtures } from '../search/search-service'
import { aiService } from './ai-service'

export function AIRecommendationsPage(){
 const {properties,loading:propertiesLoading}=useProperties();const catalog=useMemo(()=>[...properties,...marketplaceFixtures].filter(p=>p.status==='published'),[properties]);const [selected,setSelected]=useState('');const [ids,setIds]=useState<string[]>([]);const [reason,setReason]=useState('');const [loading,setLoading]=useState(false);const {toast}=useToast()
 useEffect(()=>{if(!selected&&catalog[0])setSelected(catalog[0].id)},[catalog,selected])
 const find=async()=>{const property=catalog.find(p=>p.id===selected);if(!property){toast('Select a property first.','error');return}setLoading(true);try{const result=await aiService.recommend(property,catalog);const valid=result.propertyIds.filter(id=>catalog.some(p=>p.id===id&&p.id!==selected));if(!valid.length){const fallback=catalog.filter(p=>p.id!==selected).sort((a,b)=>Number(b.city===property.city)-Number(a.city===property.city)+Number(b.propertyType===property.propertyType)-Number(a.propertyType===property.propertyType)).slice(0,3).map(p=>p.id);setIds(fallback)}else setIds(valid);setReason(result.reason)}catch(e){toast(e instanceof Error?e.message:'Could not generate recommendations.','error')}finally{setLoading(false)}}
 const matches=ids.map(id=>catalog.find(p=>p.id===id)).filter((p):p is NonNullable<typeof p>=>Boolean(p));return <div className="mx-auto max-w-5xl"><p className="flex items-center gap-2 text-xs font-bold uppercase tracking-widest text-teal-700"><Sparkles className="size-4"/>Personalized discovery</p><h1 className="mt-2 font-display text-3xl font-semibold">AI similar properties</h1><p className="mt-2 text-slate-500">Choose a property and Haven AI will rank relevant alternatives by location, type, space, purpose, and price.</p><div className="mt-7 flex flex-col gap-3 rounded-2xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900 sm:flex-row"><select value={selected} onChange={e=>{setSelected(e.target.value);setIds([]);setReason('')}} disabled={propertiesLoading||!catalog.length} className="admin-select max-w-none flex-1">{catalog.map(p=><option key={p.id} value={p.id}>{p.title} · {p.area}, {p.city}</option>)}</select><Button onClick={()=>void find()} disabled={loading||!selected}>{loading?<LoaderCircle className="size-4 animate-spin"/>:<Sparkles className="size-4"/>}Find AI matches</Button></div>{reason&&<p className="mt-5 rounded-2xl bg-teal-50 p-4 text-sm text-teal-800 dark:bg-teal-950 dark:text-teal-200"><strong>Why these match:</strong> {reason}</p>}{ids.length>0&&matches.length===0&&<div className="mt-6"><EmptyState icon={<Building2/>} title="Matches are no longer available" description="The recommended properties may have been removed. Run the match again for current listings."/></div>}<div className="mt-6 grid gap-5 md:grid-cols-3">{matches.map(p=><Link key={p.id} to={`/dashboard/property/${p.id}`} className="group overflow-hidden rounded-2xl border border-slate-200 bg-white dark:border-slate-800 dark:bg-slate-900"><div className="aspect-[16/10] overflow-hidden"><img src={p.images[0]} alt={p.title} className="h-full w-full object-cover transition duration-500 group-hover:scale-105"/></div><div className="p-4"><p className="truncate font-display font-semibold">{p.title}</p><p className="mt-1 text-xs text-slate-400">{p.area}, {p.city}</p><div className="mt-4 flex items-center justify-between"><strong className="text-teal-700">${p.price.toLocaleString()}</strong><ArrowRight className="size-4 text-slate-400"/></div></div></Link>)}</div></div>
}
