import { useEffect, useState } from 'react'
import { CheckCircle2, Clock3, Mail, MoreHorizontal, Shield, Trash2, UserPlus, Users, X } from 'lucide-react'
import { z } from 'zod'
import { Button, Input, useToast } from '../../components/ui'
import { supabase } from '../../lib/supabase'
import { useAuth } from '../../lib/auth'

type Member={id:string;name:string;email:string;role:'Owner'|'Manager'|'Viewer';status:'active'|'invited';createdAt:string}
const KEY='haven-team-v1';const schema=z.object({email:z.string().email(),role:z.enum(['Manager','Viewer'])})
export function DynamicTeamPage(){const {user}=useAuth();const {toast}=useToast();const [members,setMembers]=useState<Member[]>(()=>{try{return JSON.parse(localStorage.getItem(KEY)??'[]') as Member[]}catch{return[]}});const [open,setOpen]=useState(false);const [email,setEmail]=useState('');const [role,setRole]=useState<'Manager'|'Viewer'>('Manager');const [loading,setLoading]=useState(true)
 const persist=(next:Member[])=>{setMembers(next);localStorage.setItem(KEY,JSON.stringify(next))}
 useEffect(()=>{if(!supabase||!user){setLoading(false);return}void(async()=>{const {data,error}=await supabase.from('team_members').select('id,email,role,status,created_at,profiles(full_name)').order('created_at');if(!error&&data){const rows=data.map((row:Record<string,unknown>)=>{const profile=Array.isArray(row.profiles)?row.profiles[0]:row.profiles;return{id:String(row.id),name:(profile as {full_name?:string}|null)?.full_name??String(row.email).split('@')[0],email:String(row.email),role:String(row.role) as Member['role'],status:String(row.status) as Member['status'],createdAt:String(row.created_at)}});persist(rows)}})().finally(()=>setLoading(false))},[user?.id])
 const invite=async()=>{const parsed=schema.safeParse({email,role});if(!parsed.success){toast('Enter a valid email address.','error');return}if(members.some(m=>m.email.toLowerCase()===email.toLowerCase())){toast('This person is already on your team.','error');return}const member:Member={id:crypto.randomUUID(),name:email.split('@')[0],email:email.toLowerCase(),role,status:'invited',createdAt:new Date().toISOString()};if(supabase&&user){const {data,error}=await supabase.from('team_members').insert({workspace_owner_id:user.id,email:member.email,role,status:'invited'}).select('id,created_at').single();if(error){toast(error.message,'error');return}member.id=String(data.id);member.createdAt=String(data.created_at)}persist([...members,member]);setEmail('');setOpen(false);toast('Team invitation sent.')}
 const remove=async(id:string)=>{if(supabase){const {error}=await supabase.from('team_members').delete().eq('id',id);if(error){toast(error.message,'error');return}}persist(members.filter(m=>m.id!==id));toast('Team member removed.')}
 return <div className="mx-auto max-w-5xl"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-bold uppercase tracking-wider text-teal-700">Collaboration</p><h1 className="mt-2 font-display text-3xl font-semibold">Your team</h1><p className="mt-2 text-slate-500">Invite people and control access to your property workspace.</p></div><Button onClick={()=>setOpen(true)}><UserPlus className="size-4"/>Invite teammate</Button></div><div className="mt-7 grid gap-3 sm:grid-cols-3"><Stat label="Team members" value={members.length+1}/><Stat label="Active" value={members.filter(m=>m.status==='active').length+1}/><Stat label="Pending invites" value={members.filter(m=>m.status==='invited').length}/></div><div className="mt-5 overflow-hidden rounded-2xl border border-slate-200 bg-white dark:border-slate-800 dark:bg-slate-900">{loading?<div className="p-8 text-center text-sm text-slate-400">Loading team…</div>:<><MemberRow member={{id:user?.id??'me',name:user?.name??'Workspace owner',email:user?.email??'',role:'Owner',status:'active',createdAt:user?.joinedAt??''}}/>{members.map(m=><MemberRow key={m.id} member={m} remove={()=>void remove(m.id)}/>)}</>}</div>{open&&<div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/50 p-4"><div className="w-full max-w-md rounded-3xl bg-white p-6 shadow-2xl dark:bg-slate-900"><div className="flex items-center justify-between"><div><h2 className="font-display text-xl font-semibold">Invite a teammate</h2><p className="mt-1 text-sm text-slate-500">They’ll receive secure workspace access.</p></div><button onClick={()=>setOpen(false)}><X/></button></div><label className="mt-6 block text-sm font-semibold">Email address<Input className="mt-2" type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="person@company.com"/></label><label className="mt-4 block text-sm font-semibold">Role<select className="admin-select mt-2 w-full max-w-none" value={role} onChange={e=>setRole(e.target.value as typeof role)}><option>Manager</option><option>Viewer</option></select></label><div className="mt-6 flex justify-end gap-2"><Button variant="secondary" onClick={()=>setOpen(false)}>Cancel</Button><Button onClick={()=>void invite()}><Mail className="size-4"/>Send invitation</Button></div></div></div>}</div>}
function MemberRow({member,remove}:{member:Member;remove?:()=>void}){return <div className="flex items-center gap-3 border-b border-slate-100 p-4 last:border-0 dark:border-slate-800"><span className="grid size-11 place-items-center rounded-2xl bg-teal-100 text-xs font-bold text-teal-800">{member.name.split(/[ ._-]/).map(x=>x[0]).slice(0,2).join('').toUpperCase()}</span><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{member.name}</p><p className="truncate text-xs text-slate-400">{member.email}</p></div><span className="hidden items-center gap-1 rounded-full bg-slate-100 px-2.5 py-1 text-[10px] font-bold sm:flex"><Shield className="size-3"/>{member.role}</span><span className={`flex items-center gap-1 text-xs font-semibold ${member.status==='active'?'text-emerald-600':'text-amber-600'}`}>{member.status==='active'?<CheckCircle2 className="size-4"/>:<Clock3 className="size-4"/>}{member.status}</span>{remove?<button onClick={remove} className="grid size-9 place-items-center rounded-xl text-slate-400 hover:bg-rose-50 hover:text-rose-600"><Trash2 className="size-4"/></button>:<MoreHorizontal className="size-4 text-slate-300"/>}</div>}
function Stat({label,value}:{label:string;value:number}){return <div className="rounded-2xl border border-slate-200 bg-white p-4 dark:border-slate-800 dark:bg-slate-900"><div className="flex items-center gap-2 text-xs text-slate-400"><Users className="size-4"/>{label}</div><p className="mt-2 font-display text-2xl font-semibold">{value}</p></div>}
