import type { AdminProperty, AdminReport, AdminUser } from './types'
export const adminUsers:AdminUser[]=[
{id:'u1',name:'Maya Henderson',email:'maya@havenly.com',role:'Agent',status:'active',verified:true,properties:14,joinedAt:'2024-08-12',revenue:18420},{id:'u2',name:'Daniel Foster',email:'daniel@example.com',role:'Owner',status:'active',verified:true,properties:5,joinedAt:'2025-01-19',revenue:7800},{id:'u3',name:'Sophia Chen',email:'sophia@example.com',role:'Agent',status:'active',verified:true,properties:22,joinedAt:'2024-05-04',revenue:24100},{id:'u4',name:'Omar Rahman',email:'omar@example.com',role:'Owner',status:'pending',verified:false,properties:2,joinedAt:'2026-03-19',revenue:0},{id:'u5',name:'Liam Wright',email:'liam@example.com',role:'Buyer',status:'active',verified:true,properties:0,joinedAt:'2025-11-27',revenue:320},{id:'u6',name:'Nora Blake',email:'nora@example.com',role:'Owner',status:'suspended',verified:false,properties:8,joinedAt:'2025-09-14',revenue:4100},{id:'u7',name:'Ava Martinez',email:'ava@example.com',role:'Buyer',status:'active',verified:true,properties:0,joinedAt:'2026-02-11',revenue:190},{id:'u8',name:'Noah Williams',email:'noah@example.com',role:'Owner',status:'active',verified:true,properties:3,joinedAt:'2025-12-03',revenue:3650}]
export const adminProperties:AdminProperty[]=[
{id:'p1',title:'Serene Palm Villa',owner:'Maya Henderson',city:'Austin',type:'Villa',price:1250000,status:'approved',risk:4,reports:0,createdAt:'2026-03-18',image:'/properties/modern-villa.jpg'},{id:'p2',title:'The Gallery Apartment',owner:'Daniel Foster',city:'Seattle',type:'Apartment',price:4200,status:'pending',risk:18,reports:1,createdAt:'2026-03-20',image:'/properties/city-apartment.jpg'},{id:'p3',title:'Warm Brick Townhome',owner:'Sophia Chen',city:'Denver',type:'Townhouse',price:685000,status:'sold',risk:2,reports:0,createdAt:'2026-02-14',image:'/properties/townhouse.jpg'},{id:'p4',title:'Beachfront Investment Deal',owner:'Nora Blake',city:'Miami',type:'Villa',price:180000,status:'flagged',risk:94,reports:8,createdAt:'2026-03-21',image:'/properties/modern-villa.jpg'},{id:'p5',title:'Downtown Luxury Loft',owner:'Omar Rahman',city:'New York',type:'Apartment',price:310000,status:'flagged',risk:81,reports:5,createdAt:'2026-03-22',image:'/properties/city-apartment.jpg'},{id:'p6',title:'Cedar House',owner:'Daniel Foster',city:'Portland',type:'House',price:749000,status:'approved',risk:7,reports:0,createdAt:'2026-03-11',image:'/properties/townhouse.jpg'},{id:'p7',title:'Ocean Glass Villa',owner:'Maya Henderson',city:'Miami',type:'Villa',price:2890000,status:'pending',risk:11,reports:0,createdAt:'2026-03-23',image:'/properties/modern-villa.jpg'}]
export const adminReports:AdminReport[]=[
{id:'r1',propertyId:'p4',propertyTitle:'Beachfront Investment Deal',reporter:'Alex Morgan',reason:'Fraud',details:'Price is far below market and owner requested an off-platform deposit.',status:'open',createdAt:'2026-03-23T08:30:00Z',priority:'critical'},{id:'r2',propertyId:'p5',propertyTitle:'Downtown Luxury Loft',reporter:'Jamie Lee',reason:'Duplicate',details:'Images and description appear on another listing under a different owner.',status:'investigating',createdAt:'2026-03-22T15:20:00Z',priority:'high'},{id:'r3',propertyId:'p2',propertyTitle:'The Gallery Apartment',reporter:'Taylor Reed',reason:'Misleading',details:'Square footage does not match the supplied floor plan.',status:'open',createdAt:'2026-03-21T11:05:00Z',priority:'medium'},{id:'r4',propertyId:'p4',propertyTitle:'Beachfront Investment Deal',reporter:'Sam Patel',reason:'Spam',details:'Seller sent repeated unsolicited payment instructions.',status:'open',createdAt:'2026-03-20T19:45:00Z',priority:'high'}]
export const revenueSeries=[{m:'Apr',v:41},{m:'May',v:48},{m:'Jun',v:45},{m:'Jul',v:57},{m:'Aug',v:64},{m:'Sep',v:61},{m:'Oct',v:72},{m:'Nov',v:78},{m:'Dec',v:86},{m:'Jan',v:82},{m:'Feb',v:96},{m:'Mar',v:108}]
export const categoryRevenue=[{name:'Subscriptions',value:58,color:'#0d9488'},{name:'Featured listings',value:27,color:'#f59e0b'},{name:'Agent plans',value:15,color:'#6366f1'}]
