import { useState } from 'react'
import { Link, Navigate, useNavigate } from 'react-router-dom'
import { useForm } from 'react-hook-form'
import { zodResolver } from '@hookform/resolvers/zod'
import { z } from 'zod'
import { ArrowRight, Building2, Eye, EyeOff, LoaderCircle, LockKeyhole } from 'lucide-react'
import { Button, Input, useToast } from '../../components/ui'
import { useAuth } from '../../lib/auth'

const loginSchema = z.object({ email: z.string().email('Enter a valid email address.'), password: z.string().min(8, 'Use at least 8 characters.') })
const signupSchema = loginSchema.extend({ name: z.string().min(2, 'Enter your full name.'), terms: z.literal(true, { error: 'Please accept the terms.' }) })
type LoginFields = z.infer<typeof loginSchema>
type SignupFields = z.infer<typeof signupSchema>

function AuthShell({ children, title, subtitle }: { children: React.ReactNode; title: string; subtitle: string }) {
  return <main className="grid min-h-screen lg:grid-cols-[1.05fr_.95fr]"><section className="relative hidden overflow-hidden bg-[#073b3a] p-12 text-white lg:flex lg:flex-col"><div className="absolute -right-20 -top-20 size-80 rounded-full border-[70px] border-teal-400/10"/><Link to="/" className="relative flex items-center gap-2 font-display text-xl font-bold"><span className="grid size-9 place-items-center rounded-xl bg-teal-400 text-teal-950"><Building2 className="size-5"/></span>Havenly</Link><div className="relative my-auto max-w-xl"><p className="mb-5 text-sm font-bold uppercase tracking-[.22em] text-teal-300">Property, thoughtfully managed</p><h2 className="font-display text-5xl font-semibold leading-[1.08]">The foundation for your next move.</h2><p className="mt-6 max-w-md text-lg leading-8 text-teal-50/70">A secure, beautifully simple workspace for people building their property future.</p></div><p className="relative text-sm text-teal-100/50">© 2026 Havenly, Inc. Built with care.</p></section><section className="flex items-center justify-center bg-slate-50 px-5 py-12 dark:bg-slate-950"><div className="w-full max-w-md"><Link to="/" className="mb-10 flex items-center gap-2 font-display text-xl font-bold lg:hidden"><span className="grid size-9 place-items-center rounded-xl bg-teal-600 text-white"><Building2 className="size-5"/></span>Havenly</Link><div className="mb-8"><h1 className="font-display text-3xl font-semibold tracking-tight">{title}</h1><p className="mt-2 text-slate-500 dark:text-slate-400">{subtitle}</p></div>{children}</div></section></main>
}

export function LoginPage() {
  const { user, signIn } = useAuth(); const navigate = useNavigate(); const { toast } = useToast(); const [show, setShow] = useState(false)
  const { register, handleSubmit, formState: { errors, isSubmitting }, setError } = useForm<LoginFields>({ resolver: zodResolver(loginSchema) })
  if (user) return <Navigate to="/dashboard" replace />
  const submit = async (values: LoginFields) => { try { await signIn(values.email, values.password); toast('Welcome back to Havenly.'); navigate('/dashboard') } catch (error) { setError('root', { message: error instanceof Error ? error.message : 'Unable to sign in.' }) } }
  return <AuthShell title="Welcome back" subtitle="Enter your details to access your workspace."><form onSubmit={handleSubmit(submit)} className="space-y-5"><Field label="Email address" error={errors.email?.message}><Input type="email" autoComplete="email" placeholder="you@company.com" {...register('email')}/></Field><Field label="Password" error={errors.password?.message} extra={<button type="button" className="text-sm font-semibold text-teal-700" onClick={() => toast('Password reset instructions are ready for your inbox.')}>Forgot password?</button>}><div className="relative"><Input type={show ? 'text' : 'password'} autoComplete="current-password" placeholder="••••••••" {...register('password')}/><button type="button" className="absolute right-3 top-3 text-slate-400" onClick={() => setShow(!show)} aria-label="Toggle password visibility">{show ? <EyeOff className="size-5"/> : <Eye className="size-5"/>}</button></div></Field>{errors.root && <ErrorBox message={errors.root.message}/>}<Button className="w-full" disabled={isSubmitting}>{isSubmitting ? <LoaderCircle className="size-4 animate-spin"/> : <>Sign in <ArrowRight className="size-4"/></>}</Button><p className="text-center text-sm text-slate-500">New to Havenly? <Link to="/signup" className="font-semibold text-teal-700">Create an account</Link></p></form></AuthShell>
}

export function SignupPage() {
  const { user, signUp } = useAuth(); const navigate = useNavigate(); const { toast } = useToast(); const [show, setShow] = useState(false)
  const { register, handleSubmit, formState: { errors, isSubmitting }, setError } = useForm<SignupFields>({ resolver: zodResolver(signupSchema) })
  if (user) return <Navigate to="/dashboard" replace />
  const submit = async (values: SignupFields) => { try { await signUp(values.name, values.email, values.password); toast('Your workspace is ready.'); navigate('/dashboard') } catch (error) { setError('root', { message: error instanceof Error ? error.message : 'Unable to create account.' }) } }
  return <AuthShell title="Create your account" subtitle="Set up your secure Havenly workspace."><form onSubmit={handleSubmit(submit)} className="space-y-4"><Field label="Full name" error={errors.name?.message}><Input autoComplete="name" placeholder="Alex Morgan" {...register('name')}/></Field><Field label="Email address" error={errors.email?.message}><Input type="email" autoComplete="email" placeholder="you@company.com" {...register('email')}/></Field><Field label="Password" error={errors.password?.message}><div className="relative"><Input type={show ? 'text' : 'password'} autoComplete="new-password" placeholder="At least 8 characters" {...register('password')}/><button type="button" className="absolute right-3 top-3 text-slate-400" onClick={() => setShow(!show)} aria-label="Toggle password visibility">{show ? <EyeOff className="size-5"/> : <Eye className="size-5"/>}</button></div></Field><label className="flex items-start gap-3 text-sm text-slate-600 dark:text-slate-400"><input type="checkbox" className="mt-1 accent-teal-600" {...register('terms')}/>I agree to the Terms of Service and Privacy Policy.</label>{errors.terms && <p className="text-xs font-medium text-rose-600">{errors.terms.message}</p>}{errors.root && <ErrorBox message={errors.root.message}/>}<Button className="w-full" disabled={isSubmitting}>{isSubmitting ? <LoaderCircle className="size-4 animate-spin"/> : <>Create account <ArrowRight className="size-4"/></>}</Button><p className="text-center text-sm text-slate-500">Already have an account? <Link to="/login" className="font-semibold text-teal-700">Sign in</Link></p></form></AuthShell>
}

function Field({ label, error, extra, children }: { label: string; error?: string; extra?: React.ReactNode; children: React.ReactNode }) { return <label className="block"><span className="mb-2 flex justify-between text-sm font-semibold text-slate-700 dark:text-slate-300"><span>{label}</span>{extra}</span>{children}{error && <span className="mt-1.5 block text-xs font-medium text-rose-600">{error}</span>}</label> }
function ErrorBox({ message }: { message?: string }) { return <div className="flex items-center gap-2 rounded-xl bg-rose-50 p-3 text-sm text-rose-700 dark:bg-rose-950/50 dark:text-rose-300"><LockKeyhole className="size-4"/>{message}</div> }
