import { createContext, useCallback, useContext, useEffect, useMemo, useState, type ReactNode } from 'react'
import { useAuth } from '../../lib/auth'
import { supabase } from '../../lib/supabase'
import { defaultPreferences, type AppNotification, type NotificationPreferences, type NotificationType } from './types'

const NOTIFICATIONS_KEY='haven-notifications-v2';const PREFS_KEY='haven-notification-preferences-v1'
type Value={notifications:AppNotification[];unreadCount:number;preferences:NotificationPreferences;loading:boolean;markRead:(id:string)=>Promise<void>;markAllRead:()=>Promise<void>;remove:(id:string)=>Promise<void>;clearRead:()=>Promise<void>;updatePreferences:(next:NotificationPreferences)=>Promise<void>;push:(input:{type:NotificationType;title:string;body:string;actionUrl?:string;imageUrl?:string})=>Promise<void>}
const Context=createContext<Value|null>(null)
function load<T>(key:string,fallback:T):T{try{const value=localStorage.getItem(key);return value?JSON.parse(value) as T:fallback}catch{return fallback}}
function fromRow(row:Record<string,unknown>):AppNotification{return{id:String(row.id),userId:String(row.user_id),type:String(row.type) as NotificationType,title:String(row.title),body:String(row.body),actionUrl:row.action_url?String(row.action_url):null,imageUrl:row.image_url?String(row.image_url):null,readAt:row.read_at?String(row.read_at):null,createdAt:String(row.created_at),metadata:(row.metadata??{}) as Record<string,string>}}
export function NotificationProvider({children}:{children:ReactNode}){const {user}=useAuth();const [notifications,setNotifications]=useState<AppNotification[]>(()=>supabase?[]:load(NOTIFICATIONS_KEY,[]));const [preferences,setPreferences]=useState<NotificationPreferences>(()=>load(PREFS_KEY,defaultPreferences));const [loading,setLoading]=useState(true);const persist=useCallback((next:AppNotification[])=>{setNotifications(next);if(!supabase)localStorage.setItem(NOTIFICATIONS_KEY,JSON.stringify(next))},[])
 const refresh=useCallback(async()=>{if(!supabase||!user){setLoading(false);return}setLoading(true);const [{data:rows,error},{data:prefs}]=await Promise.all([supabase.from('notifications').select('*').eq('user_id',user.id).order('created_at',{ascending:false}).limit(100),supabase.from('notification_preferences').select('*').eq('user_id',user.id).maybeSingle()]);if(!error&&rows)setNotifications(rows.map(row=>fromRow(row)));if(prefs){const next={inApp:Boolean(prefs.in_app),email:Boolean(prefs.email),new_message:Boolean(prefs.new_message),property_approved:Boolean(prefs.property_approved),property_rejected:Boolean(prefs.property_rejected),property_sold:Boolean(prefs.property_sold),favorite_updated:Boolean(prefs.favorite_updated),support:Boolean(prefs.support)};setPreferences(next);localStorage.setItem(PREFS_KEY,JSON.stringify(next))}setLoading(false)},[user])
 useEffect(()=>{void refresh()},[refresh])
 useEffect(()=>{if(!supabase||!user)return;const channel=supabase.channel(`notifications:${user.id}`).on('postgres_changes',{event:'INSERT',schema:'public',table:'notifications',filter:`user_id=eq.${user.id}`},payload=>{const incoming=fromRow(payload.new);setNotifications(current=>current.some(item=>item.id===incoming.id)?current:[incoming,...current]);if(document.hidden&&'Notification'in window&&Notification.permission==='granted')new Notification(incoming.title,{body:incoming.body,icon:'/favicon.svg'})}).on('postgres_changes',{event:'UPDATE',schema:'public',table:'notifications',filter:`user_id=eq.${user.id}`},payload=>{const changed=fromRow(payload.new);setNotifications(current=>current.map(item=>item.id===changed.id?changed:item))}).on('postgres_changes',{event:'DELETE',schema:'public',table:'notifications',filter:`user_id=eq.${user.id}`},payload=>setNotifications(current=>current.filter(item=>item.id!==String(payload.old.id)))).subscribe();return()=>{void supabase.removeChannel(channel)}},[user])
 const markRead=async(id:string)=>{const at=new Date().toISOString();persist(notifications.map(item=>item.id===id?{...item,readAt:at}:item));if(supabase&&user){const {error}=await supabase.from('notifications').update({read_at:at}).eq('id',id).eq('user_id',user.id);if(error)await refresh()}}
 const markAllRead=async()=>{const at=new Date().toISOString();persist(notifications.map(item=>({...item,readAt:item.readAt??at})));if(supabase&&user){const {error}=await supabase.rpc('mark_all_notifications_read');if(error)await refresh()}}
 const remove=async(id:string)=>{persist(notifications.filter(item=>item.id!==id));if(supabase&&user){const {error}=await supabase.from('notifications').delete().eq('id',id).eq('user_id',user.id);if(error)await refresh()}}
 const clearRead=async()=>{persist(notifications.filter(item=>!item.readAt));if(supabase&&user){const {error}=await supabase.from('notifications').delete().eq('user_id',user.id).not('read_at','is',null);if(error)await refresh()}}
 const updatePreferences=async(next:NotificationPreferences)=>{setPreferences(next);localStorage.setItem(PREFS_KEY,JSON.stringify(next));if(supabase&&user){const row={user_id:user.id,in_app:next.inApp,email:next.email,new_message:next.new_message,property_approved:next.property_approved,property_rejected:next.property_rejected,property_sold:next.property_sold,favorite_updated:next.favorite_updated,support:next.support};const {error}=await supabase.from('notification_preferences').upsert(row,{onConflict:'user_id'});if(error)throw new Error(error.message)}}
 const push=async(input:{type:NotificationType;title:string;body:string;actionUrl?:string;imageUrl?:string})=>{if(!user||!preferences.inApp||!preferences[input.type])return;if(supabase){const {error}=await supabase.from('notifications').insert({user_id:user.id,type:input.type,title:input.title,body:input.body,action_url:input.actionUrl??null,image_url:input.imageUrl??null});if(error)throw new Error(error.message);return}persist([{id:crypto.randomUUID(),userId:user.id,type:input.type,title:input.title,body:input.body,actionUrl:input.actionUrl??null,imageUrl:input.imageUrl??null,readAt:null,createdAt:new Date().toISOString(),metadata:{}},...notifications])}
 const sorted=useMemo(()=>[...notifications].sort((a,b)=>Date.parse(b.createdAt)-Date.parse(a.createdAt)),[notifications]);const value=useMemo(()=>({notifications:sorted,unreadCount:sorted.filter(item=>!item.readAt).length,preferences,loading,markRead,markAllRead,remove,clearRead,updatePreferences,push}),[sorted,preferences,loading]);return <Context.Provider value={value}>{children}</Context.Provider>}
export function useNotifications(){const value=useContext(Context);if(!value)throw new Error('useNotifications requires NotificationProvider');return value}
