import { createContext, useCallback, useContext, useEffect, useMemo, useState, type ReactNode } from 'react'
import type { RealtimeChannel } from '@supabase/supabase-js'
import { useAuth } from '../../lib/auth'
import { supabase } from '../../lib/supabase'
import { createConversation, loadSnapshot, saveSnapshot, toMessage, uploadMessageImage } from './messaging-service'
import type { ChatMessage, Conversation, MessagingSnapshot } from './types'

type ContextValue={conversations:Conversation[];messages:Record<string,ChatMessage[]>;typing:Record<string,boolean>;online:boolean;openForProperty:(id:string,title:string,image:string,sellerId?:string)=>Promise<string>;send:(conversationId:string,body:string,file?:File)=>Promise<void>;markRead:(conversationId:string)=>Promise<void>;setTyping:(conversationId:string,value:boolean)=>void;refresh:()=>Promise<void>}
const Context=createContext<ContextValue|null>(null)
export function MessagingProvider({children}:{children:ReactNode}){const {user}=useAuth();const [snapshot,setSnapshot]=useState<MessagingSnapshot>(()=>supabase?{conversations:[],messages:{}}:loadSnapshot());const [typing,setTypingState]=useState<Record<string,boolean>>({});const [online,setOnline]=useState(navigator.onLine)
 const update=useCallback((fn:(current:MessagingSnapshot)=>MessagingSnapshot)=>setSnapshot(current=>{const next=fn(current);if(!supabase)saveSnapshot(next);return next}),[])
 const refresh=useCallback(async()=>{if(!supabase||!user)return;const {data:members,error}=await supabase.from('conversation_members').select('conversation_id, conversations(id,property_id,updated_at)').eq('user_id',user.id);if(error)throw error;if(!members?.length){setSnapshot({conversations:[],messages:{}});return}const ids=members.map(row=>String(row.conversation_id));const propertyIds=members.map(row=>String((row.conversations as unknown as {property_id:string}|null)?.property_id)).filter(Boolean);const [{data:rows},{data:messageRows}]=await Promise.all([supabase.from('properties').select('id,title,images,owner_id').in('id',propertyIds),supabase.from('messages').select('*').in('conversation_id',ids).order('created_at',{ascending:true}).limit(1000)]);const propertyMap=new Map((rows??[]).map(row=>[String(row.id),row]));const nextMessages:Record<string,ChatMessage[]>={};for(const row of messageRows??[]){const message=toMessage(row);(nextMessages[message.conversationId]??=[]).push(message)}const conversations:Conversation[]=members.map(row=>{const conversation=row.conversations as unknown as {id:string;property_id:string;updated_at:string};const property=propertyMap.get(conversation.property_id);const list=nextMessages[conversation.id]??[];const last=list.at(-1);return{id:conversation.id,propertyId:conversation.property_id,propertyTitle:String(property?.title??'Property conversation'),propertyImage:String((property?.images as string[]|undefined)?.[0]??'/properties/modern-villa.jpg'),participants:[{id:String(property?.owner_id??'seller'),name:'Property seller',avatar:'PS',role:'seller',online:false,lastSeen:conversation.updated_at}],lastMessage:last?.body||(last?.imageUrl?'Sent an image':'Start a conversation'),lastMessageAt:last?.createdAt??conversation.updated_at,unreadCount:list.filter(message=>message.senderId!==user.id&&!message.readAt).length}});setSnapshot({conversations,messages:nextMessages})},[user])
 useEffect(()=>{if(supabase){void refresh();return}const sync=()=>setSnapshot(loadSnapshot());addEventListener('haven:messages',sync);addEventListener('storage',sync);return()=>{removeEventListener('haven:messages',sync);removeEventListener('storage',sync)}},[refresh])
 useEffect(()=>{const connected=()=>setOnline(navigator.onLine);addEventListener('online',connected);addEventListener('offline',connected);return()=>{removeEventListener('online',connected);removeEventListener('offline',connected)}},[])
 useEffect(()=>{if(!supabase||!user)return;let channel:RealtimeChannel;channel=supabase.channel(`messages:${user.id}`,{config:{presence:{key:user.id}}}).on('postgres_changes',{event:'INSERT',schema:'public',table:'messages'},payload=>{const message=toMessage(payload.new);update(current=>({...current,messages:{...current.messages,[message.conversationId]:[...(current.messages[message.conversationId]??[]).filter(m=>m.id!==message.id),message]}}))}).on('postgres_changes',{event:'UPDATE',schema:'public',table:'messages'},payload=>{const message=toMessage(payload.new);update(current=>({...current,messages:{...current.messages,[message.conversationId]:(current.messages[message.conversationId]??[]).map(m=>m.id===message.id?message:m)}}))}).on('broadcast',{event:'typing'},({payload})=>{const data=payload as {conversationId:string;userId:string;value:boolean};if(data.userId!==user.id){setTypingState(current=>({...current,[data.conversationId]:data.value}));if(data.value)setTimeout(()=>setTypingState(current=>({...current,[data.conversationId]:false})),3000)}}).on('presence',{event:'sync'},()=>setOnline(true)).subscribe(async status=>{if(status==='SUBSCRIBED')await channel.track({user_id:user.id,online_at:new Date().toISOString()})});return()=>{void supabase.removeChannel(channel)}},[update,user])
 const openForProperty=async(id:string,title:string,image:string,sellerId?:string)=>{const existing=snapshot.conversations.find(conversation=>conversation.propertyId===id);if(existing)return existing.id;if(supabase&&user){if(!sellerId)throw new Error('This property does not have a valid seller.');if(sellerId===user.id)throw new Error('You cannot start a buyer conversation with your own listing.');const {data,error}=await supabase.rpc('get_or_create_property_conversation',{target_property:id,target_seller:sellerId});if(error)throw new Error(error.message);await refresh();return String(data)}const result=createConversation(snapshot,id,title,image);setSnapshot(result.snapshot);saveSnapshot(result.snapshot);return result.conversation.id}
 const send=async(conversationId:string,body:string,file?:File)=>{if(!user)throw new Error('Sign in to send messages.');const clean=body.trim();if(!clean&&!file)return;if(clean.length>2000)throw new Error('Messages can contain up to 2,000 characters.');const id=crypto.randomUUID();let imageUrl:string|null=null;const optimistic:ChatMessage={id,conversationId,senderId:user.id,body:clean,imageUrl:null,kind:file?'image':'text',createdAt:new Date().toISOString(),readAt:null,state:'sending'};update(current=>({...current,messages:{...current.messages,[conversationId]:[...(current.messages[conversationId]??[]),optimistic]}}));try{if(file)imageUrl=await uploadMessageImage(file,user.id);if(supabase){const {error}=await supabase.from('messages').insert({id,conversation_id:conversationId,sender_id:user.id,body:clean,kind:file?'image':'text',image_url:imageUrl});if(error)throw error}const sent={...optimistic,imageUrl,state:'sent' as const};update(current=>({...current,conversations:current.conversations.map(c=>c.id===conversationId?{...c,lastMessage:file?'Sent an image':clean,lastMessageAt:sent.createdAt}:c),messages:{...current.messages,[conversationId]:(current.messages[conversationId]??[]).map(m=>m.id===id?sent:m)}}))}catch(error){update(current=>({...current,messages:{...current.messages,[conversationId]:(current.messages[conversationId]??[]).map(m=>m.id===id?{...m,state:'failed'}:m)}}));throw error}}
 const markRead=async(conversationId:string)=>{const at=new Date().toISOString();update(current=>({...current,conversations:current.conversations.map(c=>c.id===conversationId?{...c,unreadCount:0}:c),messages:{...current.messages,[conversationId]:(current.messages[conversationId]??[]).map(m=>m.senderId!==user?.id?{...m,readAt:at,state:'read'}:m)}}));if(supabase&&user)await supabase.rpc('mark_conversation_read',{target_conversation:conversationId})}
 const setTyping=(conversationId:string,value:boolean)=>{if(supabase&&user)void supabase.channel(`messages:${user.id}`).send({type:'broadcast',event:'typing',payload:{conversationId,userId:user.id,value}});else{setTypingState(current=>({...current,[conversationId]:value}));if(value)setTimeout(()=>setTypingState(current=>({...current,[conversationId]:false})),1800)}}
 const value=useMemo(()=>({conversations:snapshot.conversations,messages:snapshot.messages,typing,online,openForProperty,send,markRead,setTyping,refresh}),[snapshot,typing,online,refresh]);return <Context.Provider value={value}>{children}</Context.Provider>}
export function useMessaging(){const value=useContext(Context);if(!value)throw new Error('useMessaging requires MessagingProvider');return value}
