import { supabase } from '../../lib/supabase'
import type { ChatMessage, Conversation, MessagingSnapshot } from './types'

const KEY='haven-messaging-v1'
const now=new Date(); const ago=(minutes:number)=>new Date(now.getTime()-minutes*60000).toISOString()
const seed:MessagingSnapshot={conversations:[
 {id:'conv-maya',propertyId:'villa-01',propertyTitle:'Serene Palm Villa',propertyImage:'/properties/modern-villa.jpg',participants:[{id:'seller-maya',name:'Maya Henderson',avatar:'MH',role:'seller',online:true,lastSeen:ago(0)}],lastMessage:'Absolutely — would tomorrow at 11 work?',lastMessageAt:ago(8),unreadCount:2},
 {id:'conv-daniel',propertyId:'market-1',propertyTitle:'Cedar House',propertyImage:'/properties/townhouse.jpg',participants:[{id:'seller-daniel',name:'Daniel Foster',avatar:'DF',role:'seller',online:false,lastSeen:ago(43)}],lastMessage:'I’ve sent over the floor plan.',lastMessageAt:ago(78),unreadCount:0},
 {id:'conv-sophia',propertyId:'market-6',propertyTitle:'Canvas Apartment',propertyImage:'/properties/city-apartment.jpg',participants:[{id:'seller-sophia',name:'Sophia Chen',avatar:'SC',role:'seller',online:true,lastSeen:ago(0)}],lastMessage:'The building allows pets.',lastMessageAt:ago(1440),unreadCount:0}],messages:{
 'conv-maya':[{id:'m1',conversationId:'conv-maya',senderId:'me',body:'Hi Maya, I love the villa. Is it still available?',imageUrl:null,kind:'text',createdAt:ago(36),readAt:ago(35),state:'read'},{id:'m2',conversationId:'conv-maya',senderId:'seller-maya',body:'Hi! Yes, it is. It has had a lot of interest this week.',imageUrl:null,kind:'text',createdAt:ago(31),readAt:ago(30),state:'read'},{id:'m3',conversationId:'conv-maya',senderId:'me',body:'Could I arrange a private viewing?',imageUrl:null,kind:'text',createdAt:ago(12),readAt:ago(11),state:'read'},{id:'m4',conversationId:'conv-maya',senderId:'seller-maya',body:'Absolutely — would tomorrow at 11 work?',imageUrl:null,kind:'text',createdAt:ago(8),readAt:null,state:'sent'}],
 'conv-daniel':[{id:'m5',conversationId:'conv-daniel',senderId:'seller-daniel',body:'I’ve sent over the floor plan.',imageUrl:'/properties/townhouse.jpg',kind:'image',createdAt:ago(78),readAt:ago(70),state:'read'}],
 'conv-sophia':[{id:'m6',conversationId:'conv-sophia',senderId:'seller-sophia',body:'The building allows pets.',imageUrl:null,kind:'text',createdAt:ago(1440),readAt:ago(1430),state:'read'}]}}
export function loadSnapshot(){const value=localStorage.getItem(KEY);if(!value)return seed;try{return JSON.parse(value) as MessagingSnapshot}catch{return seed}}
export function saveSnapshot(value:MessagingSnapshot){localStorage.setItem(KEY,JSON.stringify(value));window.dispatchEvent(new CustomEvent('haven:messages'))}
export async function uploadMessageImage(file:File,userId:string){if(!file.type.startsWith('image/')||file.size>10*1024*1024)throw new Error('Choose an image under 10 MB.');if(!supabase)return await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=()=>reject(new Error('Could not read image.'));reader.readAsDataURL(file)});const ext=file.name.split('.').pop()?.toLowerCase()||'jpg';const path=`${userId}/${crypto.randomUUID()}.${ext}`;const {error}=await supabase.storage.from('message-images').upload(path,file,{cacheControl:'31536000',upsert:false});if(error)throw new Error(error.message);const {data}=await supabase.storage.from('message-images').createSignedUrl(path,3600);if(!data?.signedUrl)throw new Error('Could not secure the image URL.');return data.signedUrl}
export function createConversation(snapshot:MessagingSnapshot,propertyId:string,title:string,image:string):{snapshot:MessagingSnapshot;conversation:Conversation}{const existing=snapshot.conversations.find(c=>c.propertyId===propertyId);if(existing)return{snapshot,conversation:existing};const conversation:Conversation={id:crypto.randomUUID(),propertyId,propertyTitle:title,propertyImage:image,participants:[{id:'seller-maya',name:'Maya Henderson',avatar:'MH',role:'seller',online:true,lastSeen:new Date().toISOString()}],lastMessage:'Start a conversation',lastMessageAt:new Date().toISOString(),unreadCount:0};return{conversation,snapshot:{...snapshot,conversations:[conversation,...snapshot.conversations],messages:{...snapshot.messages,[conversation.id]:[]}}}}
export function toMessage(row:Record<string,unknown>):ChatMessage{return{id:String(row.id),conversationId:String(row.conversation_id),senderId:String(row.sender_id),body:String(row.body??''),imageUrl:row.image_url?String(row.image_url):null,kind:row.kind==='image'?'image':'text',createdAt:String(row.created_at),readAt:row.read_at?String(row.read_at):null,state:row.read_at?'read':'sent'}}
