import { useEffect, useRef, useState } from 'react'
import { LocateFixed } from 'lucide-react'
import { KARACHI_BOUNDS, KARACHI_CENTER, isInKarachi } from '../../lib/karachi'
import { Input } from '../../components/ui'

type LatLng={lat:number;lng:number}
type MapEvent={latLng:{lat:()=>number;lng:()=>number}}
type GoogleMap={addListener:(name:string,handler:(event:MapEvent)=>void)=>void;fitBounds:(bounds:unknown)=>void}
type GoogleMarker={setPosition:(position:LatLng)=>void;addListener:(name:string,handler:()=>void)=>void;getPosition:()=>{lat:()=>number;lng:()=>number}}
type MapsAPI={Map:new(element:HTMLElement,options:Record<string,unknown>)=>GoogleMap;Marker:new(options:Record<string,unknown>)=>GoogleMarker;LatLngBounds:new(sw:LatLng,ne:LatLng)=>unknown}
declare global{interface Window{google?:{maps:MapsAPI};__havenMapsPromise?:Promise<void>}}
const apiKey=import.meta.env.VITE_GOOGLE_MAPS_API_KEY as string|undefined
function loadMaps(){if(window.google)return Promise.resolve();if(window.__havenMapsPromise)return window.__havenMapsPromise;window.__havenMapsPromise=new Promise((resolve,reject)=>{const timeout=window.setTimeout(()=>reject(new Error('Google Maps timed out. Check API key restrictions.')),12000);const script=document.createElement('script');script.src=`https://maps.googleapis.com/maps/api/js?key=${encodeURIComponent(apiKey??'')}&v=weekly&loading=async`;script.async=true;script.onload=()=>{clearTimeout(timeout);window.google?resolve():reject(new Error('Google Maps rejected the configured key.'))};script.onerror=()=>{clearTimeout(timeout);reject(new Error('Google Maps could not load. Enable Maps JavaScript API.'))};document.head.appendChild(script)});return window.__havenMapsPromise}
export function GoogleMapPicker({latitude,longitude,onChange,error}:{latitude:number;longitude:number;onChange:(position:LatLng)=>void;error?:string}){const host=useRef<HTMLDivElement>(null);const [mapError,setMapError]=useState('');const lat=latitude||KARACHI_CENTER.lat;const lng=longitude||KARACHI_CENTER.lng;useEffect(()=>{if(!apiKey){setMapError('Interactive pin editing requires a restricted Google Maps browser key.');return}let active=true;void loadMaps().then(()=>{if(!active||!host.current||!window.google)return;const maps=window.google.maps;const position={lat,lng};const map=new maps.Map(host.current,{center:position,zoom:14,mapTypeControl:false,streetViewControl:false,fullscreenControl:true,restriction:{latLngBounds:KARACHI_BOUNDS,strictBounds:true}});const marker=new maps.Marker({map,position,draggable:true});const apply=(p:LatLng)=>{if(isInKarachi(p.lat,p.lng)){marker.setPosition(p);onChange(p);setMapError('')}else setMapError('The pin must be within Karachi.')};map.addListener('click',event=>apply({lat:event.latLng.lat(),lng:event.latLng.lng()}));marker.addListener('dragend',()=>{const p=marker.getPosition();apply({lat:p.lat(),lng:p.lng()})})}).catch(cause=>setMapError(cause instanceof Error?cause.message:'Map unavailable.'));return()=>{active=false}},[]);const coordinate=(key:'lat'|'lng',value:string)=>{const parsed=Number(value);if(Number.isFinite(parsed))onChange(key==='lat'?{lat:parsed,lng:longitude}:{lat:latitude,lng:parsed})};return <div><div className="relative h-72 overflow-hidden rounded-2xl border border-slate-200 bg-slate-100 dark:border-slate-700 dark:bg-slate-800"><div ref={host} className="absolute inset-0"/>{!apiKey&&<iframe title="Karachi property map" src={`https://www.google.com/maps?q=${encodeURIComponent(`${lat},${lng}`)}&z=15&output=embed`} className="absolute inset-0 h-full w-full border-0" loading="lazy" referrerPolicy="no-referrer-when-downgrade"/>}</div><div className="mt-3 grid grid-cols-2 gap-3"><label className="text-xs font-semibold">Latitude<Input type="number" step="any" value={latitude||''} onChange={e=>coordinate('lat',e.target.value)} placeholder="24.8607"/></label><label className="text-xs font-semibold">Longitude<Input type="number" step="any" value={longitude||''} onChange={e=>coordinate('lng',e.target.value)} placeholder="67.0011"/></label></div><p className={`mt-2 flex items-center gap-1 text-xs ${error||mapError?'text-amber-700 dark:text-amber-400':'text-slate-400'}`}><LocateFixed className="size-3"/>{error||mapError||'Click the map or drag the pin to the property entrance.'}</p></div>}
