import { useRef, useState } from 'react'
import { GripVertical, ImagePlus, LoaderCircle, Sparkles, Trash2, UploadCloud } from 'lucide-react'
import { useAuth } from '../../lib/auth'
import { uploadPropertyImage } from './image-service'
import { useToast } from '../../components/ui'

export function ImageUploader({ value, onChange, error }: { value: string[]; onChange: (images: string[]) => void; error?: string }) {
  const input = useRef<HTMLInputElement>(null); const [active, setActive] = useState(false); const [uploading, setUploading] = useState(0); const [dragIndex, setDragIndex] = useState<number | null>(null); const { user } = useAuth(); const { toast } = useToast()
  const process = async (files: File[]) => {
    const available = 12 - value.length; const selected = files.slice(0, available).filter((file) => file.type.startsWith('image/') && file.size <= 15 * 1024 * 1024)
    if (!selected.length) { toast('Choose JPG, PNG, or WebP images under 15 MB.', 'error'); return }
    setUploading(selected.length)
    const uploaded: string[] = []
    for (const file of selected) { try { uploaded.push(await uploadPropertyImage(file, user?.id ?? 'owner')) } catch (err) { toast(err instanceof Error ? err.message : 'Upload failed.', 'error') } finally { setUploading((n) => n - 1) } }
    onChange([...value, ...uploaded]); if (files.length > available) toast('Only the first 12 images were added.')
  }
  const drop = (event: React.DragEvent) => { event.preventDefault(); setActive(false); void process(Array.from(event.dataTransfer.files)) }
  const reorder = (target: number) => { if (dragIndex === null || dragIndex === target) return; const next = [...value]; const [image] = next.splice(dragIndex, 1); next.splice(target, 0, image); onChange(next); setDragIndex(null) }
  return <div><div onDragOver={(e) => { e.preventDefault(); setActive(true) }} onDragLeave={() => setActive(false)} onDrop={drop} className={`relative flex min-h-44 flex-col items-center justify-center rounded-2xl border-2 border-dashed p-6 text-center transition ${active ? 'border-teal-500 bg-teal-50 dark:bg-teal-950/40' : error ? 'border-rose-300 bg-rose-50/40 dark:bg-rose-950/20' : 'border-slate-200 bg-slate-50/60 hover:border-teal-400 dark:border-slate-700 dark:bg-slate-950/40'}`}><input ref={input} type="file" accept="image/jpeg,image/png,image/webp" multiple className="hidden" onChange={(e) => { void process(Array.from(e.target.files ?? [])); e.target.value = '' }}/>{uploading ? <><LoaderCircle className="size-9 animate-spin text-teal-600"/><p className="mt-3 font-semibold">Optimizing & uploading {uploading} image{uploading > 1 ? 's' : ''}…</p></> : <><span className="grid size-12 place-items-center rounded-2xl bg-white text-teal-700 shadow-sm dark:bg-slate-900"><UploadCloud/></span><p className="mt-3 font-semibold">Drop property photos here</p><p className="mt-1 text-sm text-slate-500">or <button type="button" onClick={() => input.current?.click()} className="font-semibold text-teal-700 dark:text-teal-400">browse your files</button></p><p className="mt-3 flex items-center gap-1 text-xs text-slate-400"><Sparkles className="size-3"/>Images are automatically compressed and converted to WebP</p></>}</div>{error && <p className="mt-2 text-xs font-medium text-rose-600">{error}</p>}{value.length > 0 && <><div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-4">{value.map((image, index) => <div key={`${image.slice(-30)}-${index}`} draggable onDragStart={() => setDragIndex(index)} onDragOver={(e) => e.preventDefault()} onDrop={() => reorder(index)} className="group relative aspect-[4/3] cursor-grab overflow-hidden rounded-xl bg-slate-100"><img src={image} alt={`Property image ${index + 1}`} className="h-full w-full object-cover"/>{index === 0 && <span className="absolute left-2 top-2 rounded-md bg-slate-950/75 px-2 py-1 text-[10px] font-bold text-white">COVER</span>}<span className="absolute bottom-2 left-2 rounded-md bg-slate-950/60 p-1 text-white opacity-0 transition group-hover:opacity-100"><GripVertical className="size-4"/></span><button type="button" onClick={() => onChange(value.filter((_, i) => i !== index))} className="absolute right-2 top-2 grid size-8 place-items-center rounded-lg bg-white/90 text-rose-600 opacity-0 shadow transition hover:bg-white group-hover:opacity-100" aria-label="Remove image"><Trash2 className="size-4"/></button></div>)}</div><button type="button" className="mt-3 inline-flex items-center gap-1.5 text-xs font-semibold text-teal-700 dark:text-teal-400" onClick={() => input.current?.click()}><ImagePlus className="size-4"/>Add more photos ({value.length}/12)</button></>}</div>
}
