-- Enterprise administrator authorization, reports, and immutable audit trail.
-- Assign roles only with the service-role Admin API:
-- auth.admin.updateUserById(id, { app_metadata: { role: 'admin' } }).
create or replace function public.is_admin() returns boolean language sql stable security definer set search_path=public,auth as $$select coalesce((auth.jwt()->'app_metadata'->>'role')='admin',false);$$;
revoke all on function public.is_admin() from public;grant execute on function public.is_admin() to authenticated;
create table if not exists public.property_reports(id uuid primary key default gen_random_uuid(),property_id text not null,reporter_id uuid not null references auth.users(id) on delete cascade,reason text not null check(reason in('Fraud','Duplicate','Misleading','Unavailable','Spam')),details text not null check(char_length(details) between 10 and 2000),priority text not null default 'medium' check(priority in('low','medium','high','critical')),status text not null default 'open' check(status in('open','investigating','resolved','dismissed')),assigned_to uuid references auth.users(id),created_at timestamptz not null default now(),resolved_at timestamptz);
create table if not exists public.admin_audit_logs(id bigint generated always as identity primary key,admin_id uuid not null references auth.users(id),action text not null,entity_type text not null,entity_id text not null,before_data jsonb,after_data jsonb,ip_hash text,created_at timestamptz not null default now());
create index if not exists reports_moderation_queue_idx on public.property_reports(status,priority,created_at desc);create index if not exists admin_audit_entity_idx on public.admin_audit_logs(entity_type,entity_id,created_at desc);
alter table public.property_reports enable row level security;alter table public.admin_audit_logs enable row level security;
create policy "users create reports" on public.property_reports for insert to authenticated with check(reporter_id=auth.uid());create policy "users read own reports" on public.property_reports for select to authenticated using(reporter_id=auth.uid() or public.is_admin());create policy "admins manage reports" on public.property_reports for update to authenticated using(public.is_admin()) with check(public.is_admin());create policy "admins read audit log" on public.admin_audit_logs for select to authenticated using(public.is_admin());
-- Audit rows are written only by security-definer moderation functions or service role.
create or replace function public.moderate_report(target_report uuid,next_status text) returns void language plpgsql security definer set search_path=public as $$declare before_row jsonb;after_row jsonb;begin if not public.is_admin() then raise exception 'administrator access required' using errcode='42501';end if;if next_status not in('open','investigating','resolved','dismissed') then raise exception 'invalid report status';end if;select to_jsonb(r) into before_row from property_reports r where id=target_report for update;if before_row is null then raise exception 'report not found';end if;update property_reports set status=next_status,assigned_to=auth.uid(),resolved_at=case when next_status in('resolved','dismissed') then now() else null end where id=target_report returning to_jsonb(property_reports.*) into after_row;insert into admin_audit_logs(admin_id,action,entity_type,entity_id,before_data,after_data) values(auth.uid(),'moderate_report','property_report',target_report::text,before_row,after_row);end;$$;
revoke all on function public.moderate_report(uuid,text) from public;grant execute on function public.moderate_report(uuid,text) to authenticated;
