-- Karachi-only, fully dynamic property catalog.
create table if not exists public.properties(id uuid primary key default gen_random_uuid(),owner_id uuid not null references auth.users(id) on delete cascade,title text not null check(char_length(title) between 5 and 100),description text not null check(char_length(description) between 30 and 3000),price numeric(14,2) not null check(price>0),purpose text not null check(purpose in('sale','rent')),property_type text not null check(property_type in('house','apartment','villa','townhouse','land','commercial')),bedrooms int not null default 0 check(bedrooms between 0 and 100),bathrooms int not null default 0 check(bathrooms between 0 and 100),kitchen int not null default 0,parking int not null default 0,square_feet int not null check(square_feet>=50),city text not null default 'Karachi' check(city='Karachi'),area text not null check(area in('Bahadurabad','Buffer Zone','Clifton','Defence View','DHA','Federal B Area','Garden','Gulistan-e-Johar','Gulshan-e-Iqbal','Karsaz','Keamari','Korangi','Landhi','Liaquatabad','Malir','Nazimabad','North Karachi','North Nazimabad','PECHS','Saddar','Scheme 33','Shah Faisal Colony')),address text not null,latitude double precision not null check(latitude between 24.45 and 25.55),longitude double precision not null check(longitude between 66.55 and 67.65),images text[] not null check(cardinality(images) between 1 and 12),status text not null default 'draft' check(status in('draft','published','archived','sold','rented')),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.favorites(user_id uuid not null references auth.users(id) on delete cascade,property_id uuid not null references public.properties(id) on delete cascade,created_at timestamptz not null default now(),primary key(user_id,property_id));
create index if not exists properties_public_feed_idx on public.properties(status,created_at desc,id desc);create index if not exists properties_karachi_area_idx on public.properties(area,purpose,property_type,price) where status='published';create index if not exists properties_rooms_idx on public.properties(bedrooms,bathrooms) where status='published';create index if not exists favorites_user_idx on public.favorites(user_id,created_at desc);
alter table public.properties enable row level security;alter table public.favorites enable row level security;
create policy "public reads published properties" on public.properties for select using(status='published' or owner_id=auth.uid() or public.is_admin());create policy "owners create Karachi properties" on public.properties for insert to authenticated with check(owner_id=auth.uid() and city='Karachi');create policy "owners update own properties" on public.properties for update to authenticated using(owner_id=auth.uid() or public.is_admin()) with check(owner_id=auth.uid() or public.is_admin());create policy "owners delete own properties" on public.properties for delete to authenticated using(owner_id=auth.uid() or public.is_admin());
create policy "users read own favorites" on public.favorites for select using(user_id=auth.uid());create policy "users add own favorites" on public.favorites for insert with check(user_id=auth.uid() and exists(select 1 from properties p where p.id=property_id and p.status='published'));create policy "users remove own favorites" on public.favorites for delete using(user_id=auth.uid());
create or replace function public.touch_updated_at() returns trigger language plpgsql as $$begin new.updated_at=now();return new;end;$$;drop trigger if exists properties_touch_updated_at on public.properties;create trigger properties_touch_updated_at before update on public.properties for each row execute function public.touch_updated_at();
alter publication supabase_realtime add table public.properties;alter publication supabase_realtime add table public.favorites;
