-- Durable, user-scoped notifications with realtime delivery and email outbox.
create table if not exists public.notifications(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,type text not null check(type in('new_message','property_approved','property_rejected','property_sold','favorite_updated','support')),title text not null check(char_length(title) between 1 and 120),body text not null check(char_length(body) between 1 and 500),action_url text,image_url text,metadata jsonb not null default '{}',read_at timestamptz,created_at timestamptz not null default now());
create table if not exists public.notification_preferences(user_id uuid primary key references auth.users(id) on delete cascade,in_app boolean not null default true,email boolean not null default true,new_message boolean not null default true,property_approved boolean not null default true,property_rejected boolean not null default true,property_sold boolean not null default true,favorite_updated boolean not null default true,support boolean not null default true,updated_at timestamptz not null default now());
create table if not exists public.notification_email_outbox(id uuid primary key default gen_random_uuid(),notification_id uuid not null unique references public.notifications(id) on delete cascade,user_id uuid not null references auth.users(id) on delete cascade,recipient text not null,status text not null default 'pending' check(status in('pending','processing','sent','failed')),attempts int not null default 0,last_error text,created_at timestamptz not null default now(),sent_at timestamptz);
create index if not exists notifications_user_feed_idx on public.notifications(user_id,created_at desc,id desc);create index if not exists notifications_unread_idx on public.notifications(user_id,created_at desc) where read_at is null;create index if not exists email_outbox_pending_idx on public.notification_email_outbox(created_at) where status='pending';
alter table public.notifications enable row level security;alter table public.notification_preferences enable row level security;alter table public.notification_email_outbox enable row level security;
create policy "users read own notifications" on public.notifications for select using(user_id=auth.uid());create policy "users update own notifications" on public.notifications for update using(user_id=auth.uid()) with check(user_id=auth.uid());create policy "users delete own notifications" on public.notifications for delete using(user_id=auth.uid());
create policy "users read preferences" on public.notification_preferences for select using(user_id=auth.uid());create policy "users create preferences" on public.notification_preferences for insert with check(user_id=auth.uid());create policy "users update preferences" on public.notification_preferences for update using(user_id=auth.uid()) with check(user_id=auth.uid());
create or replace function public.mark_all_notifications_read() returns void language sql security invoker set search_path=public as $$update notifications set read_at=coalesce(read_at,now()) where user_id=auth.uid() and read_at is null;$$;
create or replace function public.queue_notification_email() returns trigger language plpgsql security definer set search_path=public,auth as $$declare prefs public.notification_preferences;recipient_email text;begin select * into prefs from public.notification_preferences where user_id=new.user_id;if prefs.email is false or case new.type when 'new_message' then not prefs.new_message when 'property_approved' then not prefs.property_approved when 'property_rejected' then not prefs.property_rejected when 'property_sold' then not prefs.property_sold when 'favorite_updated' then not prefs.favorite_updated when 'support' then not prefs.support else true end then return new;end if;select email into recipient_email from auth.users where id=new.user_id;if recipient_email is not null then insert into public.notification_email_outbox(notification_id,user_id,recipient) values(new.id,new.user_id,recipient_email) on conflict do nothing;end if;return new;end;$$;
drop trigger if exists queue_notification_email on public.notifications;create trigger queue_notification_email after insert on public.notifications for each row execute function public.queue_notification_email();
-- Fan out a message notification to every recipient. The database, not the
-- browser, is authoritative so offline recipients still receive the event.
create or replace function public.notify_conversation_message() returns trigger language plpgsql security definer set search_path=public as $$begin insert into notifications(user_id,type,title,body,action_url,metadata) select cm.user_id,'new_message','New message',case when new.kind='image' then 'Sent you an image' else left(new.body,180) end,'/dashboard/messages?conversation='||new.conversation_id,jsonb_build_object('conversationId',new.conversation_id,'messageId',new.id) from conversation_members cm where cm.conversation_id=new.conversation_id and cm.user_id<>new.sender_id;return new;end;$$;
drop trigger if exists notify_conversation_message on public.messages;create trigger notify_conversation_message after insert on public.messages for each row execute function public.notify_conversation_message();
alter publication supabase_realtime add table public.notifications;
